/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module ref6(clk, reset, req_a, req_b, grant_a, grant_b);
  wire _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire clk;
  output grant_a;
  wire grant_a;
  output grant_b;
  wire grant_b;
  wire next_state;
  input req_a;
  wire req_a;
  input req_b;
  wire req_b;
  input reset;
  wire reset;
  reg state;
  always @(posedge clk)
    if (reset) state <= #1 1'h0;
    else state <= #1 next_state;
  assign _2_ = ~req_b;
  assign _1_ = req_b ? 1'h0 : req_a;
  assign _0_ = req_a ? 1'h0 : req_b;
  assign next_state = state ? _2_ : req_a;
  assign grant_b = state ? req_b : _0_;
  assign grant_a = state ? _1_ : req_a;
endmodule
