/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module ref1(a, b, c, m);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output m;
  wire m;
  assign _0_ = a & b;
  assign _1_ = a & c;
  assign _3_ = _0_ | _1_;
  assign _2_ = b & c;
  assign m = _3_ | _2_;
endmodule
