/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module ref7(clk, reset, r, m);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire _05_;
  input clk;
  wire clk;
  output [3:0] m;
  wire [3:0] m;
  reg [3:0] m_d1;
  input [3:0] r;
  wire [3:0] r;
  reg [3:0] r_d1;
  input reset;
  wire reset;
  always @(posedge clk)
    if (reset) r_d1[0] <= #1 1'h0;
    else r_d1[0] <= #1 r[0];
  always @(posedge clk)
    if (reset) r_d1[1] <= #1 1'h0;
    else r_d1[1] <= #1 r[1];
  always @(posedge clk)
    if (reset) r_d1[2] <= #1 1'h0;
    else r_d1[2] <= #1 r[2];
  always @(posedge clk)
    if (reset) r_d1[3] <= #1 1'h0;
    else r_d1[3] <= #1 r[3];
  always @(posedge clk)
    if (reset) m_d1[0] <= #1 1'h0;
    else m_d1[0] <= #1 m[0];
  always @(posedge clk)
    if (reset) m_d1[1] <= #1 1'h0;
    else m_d1[1] <= #1 m[1];
  always @(posedge clk)
    if (reset) m_d1[2] <= #1 1'h0;
    else m_d1[2] <= #1 m[2];
  always @(posedge clk)
    if (reset) m_d1[3] <= #1 1'h0;
    else m_d1[3] <= #1 m[3];
  assign _00_ = ~r_d1[0];
  assign _01_ = ~r_d1[1];
  assign _02_ = ~r_d1[2];
  assign _03_ = ~r_d1[3];
  assign _04_[1] = _02_ | _03_;
  assign _05_ = _04_[0] | _04_[1];
  assign _04_[0] = _00_ | _01_;
  assign m[0] = _05_ ? m_d1[0] : r[0];
  assign m[1] = _05_ ? m_d1[1] : r[1];
  assign m[2] = _05_ ? m_d1[2] : r[2];
  assign m[3] = _05_ ? m_d1[3] : r[3];
endmodule
